### Login pour récupérer le JWT
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}

> {% 
client.global.set("jwt_token", response.body.token);
%}

### Tester accès au secure-endpoint (doit marcher car ADMIN)
GET http://localhost:8080/auth/secure-endpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0Njc1ODQ0MCwiZXhwIjoxNzQ2NzYyMDQwfQ.UjiENMp2SAKpw2f-7_40_aSnO3IGBEHqkvvx2AM0RjE
Accept: application/json

### Tester accès au secure-endpoint sans token (doit échouer 401)
GET http://localhost:8080/auth/secure-endpoint
Accept: application/json
