#Créer un nouveau Realm (par ADMIN)
POST http://localhost:8080/v1/admin/realms
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNzA1MDIsImV4cCI6MTc1MzA3NDEwMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.mNl-bl4Quiqzcm7i0EMrFggg7RWqLR8wOnM482y0Ch-I2AsYdYVP3ME6Ob6-46cLFh59LhZD5_INJAzOwIyu3GN9qyWP6R0XCoiWeQ7LHl5GIQnIHrzZKWUGhW0jwNZEoEmO3Db9Zjx_bJMDbVWOvPLiWQUSQJGtOaOt4Yg0omplc4VHStslbCXhN9o4XIkAk93yNcHV5qlo1gsue3BCi-LD9_Kgq5lQxc5nZFNOkVcPV1OkOLPUIHa5CqVDvUqifImkdhCNWbjwojish43dCTSiNmvN5o7xhvOLRgmxnnStL8TheZ16ZOY7G7EtRv_sJkESfUYyRL9N7C9CeYsdow

{
"name": "client_app_a",
"description": "Realm pour l'application client A."
}

{%
client.global.set("new_realm_id", response.body.id);
%}

###
# Récupérer un Realm par ID (par ADMIN)
GET http://localhost:8080/v1/admin/realms/1
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic2NvcGVzIjpbXSwic3ViIjoibmV3dXNlciIsImlhdCI6MTc1MzA3MTI0MywiZXhwIjoxNzUzMDc0ODQzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEifQ.X1pQ3Hbix92z_voCIqoQjMe7bfqVWXF1R246Zw2VSUV8l6EbCJhdoZ2rAYX2lYhElDIESWEMjJa3AzYhdN9bQjn4g0OjI86nMMbnTyGT6aNnk0qIRUQ2mVBhUTf2hw4kNaVnW1ZW2nr-PZUWGUcZoivHn5gygRh0-AVoQXISxrhOL0_4pGUr6P9hDV-9EboxNeCl5e_HGJNBlnrSQPfmZKdLYdc4hniBUpbVHQy4Lz942irP1kAhenCoi0Axm7l5bl2PBC_c8sPL6YllBD5oqSSsmvwAYm7MXioF56h70psyrUVEHMU4yu2u_SqY35tAMRpAg6n2yvhgNoTa11TbAQ

###Récupérer tous les Realms (par ADMIN)
GET http://localhost:8080/v1/admin/realms
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic2NvcGVzIjpbXSwic3ViIjoibmV3dXNlciIsImlhdCI6MTc1MzA3MTI0MywiZXhwIjoxNzUzMDc0ODQzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEifQ.X1pQ3Hbix92z_voCIqoQjMe7bfqVWXF1R246Zw2VSUV8l6EbCJhdoZ2rAYX2lYhElDIESWEMjJa3AzYhdN9bQjn4g0OjI86nMMbnTyGT6aNnk0qIRUQ2mVBhUTf2hw4kNaVnW1ZW2nr-PZUWGUcZoivHn5gygRh0-AVoQXISxrhOL0_4pGUr6P9hDV-9EboxNeCl5e_HGJNBlnrSQPfmZKdLYdc4hniBUpbVHQy4Lz942irP1kAhenCoi0Axm7l5bl2PBC_c8sPL6YllBD5oqSSsmvwAYm7MXioF56h70psyrUVEHMU4yu2u_SqY35tAMRpAg6n2yvhgNoTa11TbAQ

###Mettre à jour un Realm (par ADMIN)
PUT http://localhost:8080/v1/admin/realms/2
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNzA1MDIsImV4cCI6MTc1MzA3NDEwMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.mNl-bl4Quiqzcm7i0EMrFggg7RWqLR8wOnM482y0Ch-I2AsYdYVP3ME6Ob6-46cLFh59LhZD5_INJAzOwIyu3GN9qyWP6R0XCoiWeQ7LHl5GIQnIHrzZKWUGhW0jwNZEoEmO3Db9Zjx_bJMDbVWOvPLiWQUSQJGtOaOt4Yg0omplc4VHStslbCXhN9o4XIkAk93yNcHV5qlo1gsue3BCi-LD9_Kgq5lQxc5nZFNOkVcPV1OkOLPUIHa5CqVDvUqifImkdhCNWbjwojish43dCTSiNmvN5o7xhvOLRgmxnnStL8TheZ16ZOY7G7EtRv_sJkESfUYyRL9N7C9CeYsdow

{
"name": "client_app_a_updated",
"description": "Realm mis à jour pour l'application client A."
}

###Supprimer un Realm (par ADMIN)
DELETE http://localhost:8080/v1/admin/realms/2
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNzA1MDIsImV4cCI6MTc1MzA3NDEwMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.mNl-bl4Quiqzcm7i0EMrFggg7RWqLR8wOnM482y0Ch-I2AsYdYVP3ME6Ob6-46cLFh59LhZD5_INJAzOwIyu3GN9qyWP6R0XCoiWeQ7LHl5GIQnIHrzZKWUGhW0jwNZEoEmO3Db9Zjx_bJMDbVWOvPLiWQUSQJGtOaOt4Yg0omplc4VHStslbCXhN9o4XIkAk93yNcHV5qlo1gsue3BCi-LD9_Kgq5lQxc5nZFNOkVcPV1OkOLPUIHa5CqVDvUqifImkdhCNWbjwojish43dCTSiNmvN5o7xhvOLRgmxnnStL8TheZ16ZOY7G7EtRv_sJkESfUYyRL9N7C9CeYsdow

 