#Créer une nouvelle permission (par ADMIN)
POST http://localhost:8080/v1/permissions
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"name": "PERM_CREATE_USER",
"scopeValue": "user:create",
"description": "Permet de créer de nouveaux utilisateurs."
}

{%
client.global.set("new_permission_id", response.body.id);
%}

###
## Récupérer une permission par ID (par ADMIN)
GET http://localhost:8080/v1/permissions/3
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

###
# Récupérer toutes les permissions (par ADMIN)
GET http://localhost:8080/v1/permissions
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

###
# Mettre à jour une permission (par ADMIN)
PUT http://localhost:8080/v1/permissions/4
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"name": "PERM_CREATE_EDIT_USER",
"scopeValue": "user:write",
"description": "Permet de créer et modifier des utilisateurs."
}

###
# Supprimer une permission (par ADMIN)
DELETE http://localhost:8080/v1/permissions/4
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

###
# Créer un nouveau rôle (par ADMIN)
POST http://localhost:8080/v1/roles
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"name": "ROLE_SUPERVISOR",
"description": "Rôle pour les gestionnaires.",
"permissionNames": ["PERM_READ", "PERM_WRITE"]
}

{%
client.global.set("new_role_id", response.body.id);
%}

###
# Récupérer un rôle par ID (par ADMIN)
GET http://localhost:8080/v1/roles/1
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ
###
# Récupérer tous les rôles (par ADMIN)
GET http://localhost:8080/v1/roles
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

###
## Mettre à jour un rôle (par ADMIN)
PUT http://localhost:8080/v1/roles/2
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"name": "ROLE_SUPERVISOR",
"description": "Rôle pour les superviseurs.",
"permissionNames": ["PERM_READ", "PERM_WRITE", "PERM_DELETE"]
}

###
# Supprimer un rôle (par ADMIN)
DELETE http://localhost:8080/v1/roles/3
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

###
### Attribuer des rôles à un utilisateur (par ADMIN)
## Assurez-vous que new_user_id et les rôles existent
POST http://localhost:8080/v1/users/2/assign-roles
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"roleNames": ["ROLE_MANAGER", "ROLE_SUPERVISOR"]
}

###
## Attribuer des permissions à un rôle (par ADMIN)
#Assurez-vous que new_role_id et les permissions existent
POST http://localhost:8080/v1/roles/2/assign-permissions
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwiZGVsZXRlIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NTMwNjYyNzQsImV4cCI6MTc1MzA2OTg3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.nHQ-YhBYeA9fjhQFWl27cW6QCXJnDPnqgQx7pxt_mj0Rrx-0rZpJWAqV7nWdNSNVmL-vayrcrvx5lVkaNOdDmopVFOYmxe2qnQAWQr-APLAqQ3q0PsUGAIuGD16Ps1dlwZEJsxnNR2tEYvB0d0Mkg4plxTXbLfnxAbvTPRkziC_xP8ThdqhuXNMTedY3tx6rcdR7zydNk7r87Vvj18WAcmt49EWZeh0tfNYr8vdqTks-8bnn0KUMo16lF6FxZWniTuwh7K0-9Bnq_b464V7ALclUzZIAYaxfC9OBIxA2e3G3EzB2MlgfKM0wxDEREBHbgYgmrevCLmKKzMYIdChzTQ

{
"permissionNames": ["PERM_READ", "PERM_WRITE"]
}