spring.application.name=iam
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Password Policy Configuration
password.policy.min-length=8
password.policy.require-uppercase=true
password.policy.require-lowercase=true
password.policy.require-digit=true
password.policy.require-special-char=true 

# Configuration de la politique de verrouillage de compte
account.lockout.max-attempts=2
account.lockout.duration-minutes=2
jwt.refresh-token.expiration-days:7
password.reset.token-expiration-hours:1

# Notification Service Configuration
notification.service.url=http://localhost:8085

# --- RabbitMQ Configuration ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Noms des échanges et clés de routage (par défaut si non spécifié)
rabbitmq.notification.exchange.name=notification-exchange
rabbitmq.notification.routing-keys.verification=email.verification
rabbitmq.notification.routing-keys.password-reset=email.password.reset

# --- Eureka Client Configuration ---
spring.application.name=iam-service # Nom du service IAM pour Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka # URL de votre serveur Eureka
eureka.instance.hostname=localhost # Nom d'hôte de cette instance (pour le développement)
eureka.client.enabled=true # Activer le client Eureka
