spring.application.name=iam
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Password Policy Configuration
password.policy.min-length=8
password.policy.require-uppercase=true
password.policy.require-lowercase=true
password.policy.require-digit=true
password.policy.require-special-char=true 

# Configuration de la politique de verrouillage de compte
account.lockout.max-attempts=2
account.lockout.duration-minutes=2
jwt.refresh-token.expiration-days:7
password.reset.token-expiration-hours:1

# Notification Service Configuration
notification.service.url=http://localhost:8085
